name: Flutter CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - run: flutter pub get
      - name: Run flutter analyze (ignore warnings)
        run: flutter analyze --no-fatal-warnings --no-fatal-infos
      - run: flutter test
      
  build-android:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - run: flutter pub get
      - run: flutter build appbundle --release --obfuscate --split-debug-info=build/debug-info
      - name: Upload app bundle
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
          
  build-apk:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - run: flutter pub get
      - run: flutter build apk --release --obfuscate --split-debug-info=build/debug-info
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk 